# Streamlit secrets configuration
# Add any API keys or sensitive configuration here

[database]
path = "market_intelligence.db"
backup_enabled = true

[app]
debug_mode = false
demo_data_enabled = true

# Email configuration (for alerts)
[email]
# smtp_server = ""
# smtp_port = 587
# username = ""
# password = ""